const GET_TOOLS_BY_NAME = "GET_TOOLS_BY_NAME";
const GET_TOOLS = "GET_TOOLS";
const GET_TOOLS_BY_ID = "GET_TOOLS_BY_ID";
const CREATE_USER = "CREATE_USER";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const LESS_FROM_CART = "LESS_FROM_CART"
const ORDER_BY_NAME = "ORDER_BY_NAME";
const ORDER_BY_PRICE = "ORDER_BY_PRICE";
const SET_CURRRENT_PAGE = "SET_CURRENT_PAGE";
const GET_USER = "GET_USER";
const CLEAN_BDD = "CLEAN_BDD"
const CHANGE_FILTER_CATEGORY = "CHANGE_FILTER_CATEGORY";
const CHANGE_FILTER_BRAND = "CHANGE_FILTER_BRAND";
const CERRAR_SESION = "CERRAR_SESION";
const LOGIN = "LOGIN";
const VERIFY_LOGIN_SUCCESS = "VERIFY_LOGIN_SUCCESS"
const ERROR_LOGIN = "ERROR_LOGIN"
const ISAUTHENTICATED = "ISAUTHENTICATED"
const UPDATE_TOOL_STOCK = 'UPDATE_TOOL_STOCK';
const REGISTER_STOCK_ENTRY_SUCCESS = 'REGISTER_STOCK_ENTRY_SUCCESS';
const REGISTER_STOCK_ENTRY_FAILURE = 'REGISTER_STOCK_ENTRY_FAILURE';
const REGISTER_STOCK_EXIT_SUCCESS = 'REGISTER_STOCK_EXIT_SUCCESS';
const REGISTER_STOCK_EXIT_FAILURE = 'REGISTER_STOCK_EXIT_FAILURE';
const ACTUAL_USER = "ACTUAL_USER";

export {
  GET_TOOLS_BY_NAME,
  GET_TOOLS,
  GET_TOOLS_BY_ID,
  CREATE_USER,
  GET_USER,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  LESS_FROM_CART,
  ORDER_BY_NAME,
  ORDER_BY_PRICE,
  SET_CURRRENT_PAGE,
  CLEAN_BDD,
  CHANGE_FILTER_CATEGORY,
  CHANGE_FILTER_BRAND,
  CERRAR_SESION,
  LOGIN,
  VERIFY_LOGIN_SUCCESS,
  ERROR_LOGIN,
  ISAUTHENTICATED,
  UPDATE_TOOL_STOCK,
  REGISTER_STOCK_ENTRY_SUCCESS,
  REGISTER_STOCK_EXIT_FAILURE,
  REGISTER_STOCK_EXIT_SUCCESS,
  REGISTER_STOCK_ENTRY_FAILURE,
  ACTUAL_USER
};
